apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
   app:  {{ .Values.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "s5michel-espresso-shop-web3.selectorLabels" . | nindent 4 }}
